### ISSUE TITLE
Reauthorize on every shutdown

### ISSUE THREAD

**Issue by Beariful** [fredemmott/StreamDeck-Discord#2] opened 2019-02-05 01:14 UTC
I have to re-enter the App ID every time I turn my computer back on. I have seen this issue multiple times. I remove the last digit from the App ID, then add it back in to reauthorize the application every time I start my computer. I have followed the instructions and tried removing everything and recreating it. After re-entering the App ID it works just fine, until the next restart.

**Comment by ntoff** [comment] 2019-02-06 09:45
I have a similar issue but it's not every restart, it's just every now and then.

**Comment by fredemmott** [comment] 2019-02-06 16:40
When did you install? I'm hopeful that these issues were fixed in v1.3 on 1/20 - you might need to download the new version from https://github.com/fredemmott/StreamDeck-Discord/releases/latest/

**Comment by ntoff** [comment] 2019-02-06 16:44
I'm using v1.3 already (according to the more actions menu with all the available / installed plugins).

**Comment by Beariful** [comment] 2019-02-06 22:10
same here v1.3. I have seen it on every restart expect today, it synced fine.

**Comment by eliasthompson** [comment] 2019-02-24 10:21
+1. Downloaded v1.3, got it set up, restarted, and had to do the last digit fix that Beariful said to get it working again.

**Comment by fredemmott** [comment] 2019-03-02 22:33
This should be fixed with v2.0: https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v2.0

**Comment by fredemmott** [comment] 2019-03-03 01:31
- relink button should help
- everything except shutdown stuff should be fixed
- that should be /much better/ but isn't entirely fixed

I managed to reproduce this once by:

1. quit discord completely
2. quit streamdeck
3. start streamdeck
4. spam the button like crazy
5. wait 5 seconds
6. start discord

However, I could only make this go wrong once. I've tried a bunch and it usually ends up connecting fine. If someone's able to figure out reliable steps to reproduce, that'll make fixing this properly much better.

**Comment by fredemmott** [comment] 2019-03-03 01:55
Also, when it's not working, can you open Task Manager, and find 'Stream Deck' - if you expand it, you should see somethings like "Qt Qtwebengineprocess" - do you also see `sddiscord.exe` there?

**Comment by ntoff** [comment] 2019-03-03 01:57
>However, I could only make this go wrong once.

Yep, unlike the others, for me it only ever happens once in a while. I'll give this version a go and see, but it might take some time to tell whether it worked or not since the issue is so infrequent for me.

I guess if it makes it any easier to figure out, I don't have discord start on windows startup, I have a button on the stream deck I use to launch discord. The streamdeck software *does* launch with windows though.

**Comment by fredemmott** [comment] 2019-03-03 02:29
Yeah, I don’t think this is really caused by reboots - just that reboots mean that stream deck starts before discord, and possibly affects the timing a bit

**Comment by fredemmott** [comment] 2019-03-03 19:49
One possible cause: the buttons /always/ toggle state: if the button shows you're deafened, it will send an 'undeafen' message, even if the button states are wrong.

One way to cause an issue (fixed by button-pressing again):
- open streamdeck and discord
- unmute and undeafen in discord itself
- quit discord
- press deafen button
- open discord
- the state will update itself to undeafened and unmuted, but it will re-deafen later.

**Comment by fredemmott** [comment] 2019-03-03 20:47
Looks like I'm hitting a glitch in the streamdeck software itself: the states are correct in the software, and when the button is pressed, but not on the physical hardware. If I remove the 'setState 'code in 'willappear', changing profile's fixes it - i.e. the rendered state is changing with no action from the plugin.

So, a few follow-up questions:
- what operating system and version are you all using?
- if you open the streamdeck software, does the mute/deafen state it shows for the buttons match what you see on the actual streamdeck?

**Comment by fredemmott** [comment] 2019-03-03 20:59
So, probably not the root cause of all of these issues, but a bug is definitely not helping. Reported at https://www.reddit.com/r/StreamDeckSDK/comments/awyi3w/bug_calling_setstate_after_showokforcontext_gets/

**Comment by fredemmott** [comment] 2019-03-03 22:21
This is hopefully fixed in 2.1. If not, please:
- screenshot the expanded Debug Information section of property inspector (new)
- comment with how recent the "Last State Change" is in that section - is it seconds, minutes, or hours?
- comment with how frequently the 'last state change' is happening, if at all. It's expected to stay on 'READY' forever
- attach (or copy-paste to gist.github.com) the debug log file (new): hit win+r, then open `%APPDATA%\Elgato\StreamDeck\logs` - you want the most recent `com.fredemmott.discord.... .log` file (usually `com.fredemmott.discord0.log`).

Log file /might/ be in `%APPDATA%\Roaming\Elgato\StreamDeck\logs\` instead - this is what Elgato's documentation says, but `%APPDATA%` already includes 'roaming' on my windows machines.

On MacOS, this is `~/Library/Logs/StreamDeck/` instead.

**Comment by fredemmott** [comment] 2019-03-05 00:17
Has anyone tried v2.1 yet? Any issues?

**Comment by eliasthompson** [comment] 2019-03-05 00:36
I have 2.1 installed but haven't come across the issue recently (it did end up happening a second time, but I don't remember the circumstances around it). If I notice it again I'll try and follow the steps you outlined above.

**Comment by fredemmott** [comment] 2019-03-07 00:03
Based on the crickets, I'm guessing this is fixed - will close in a few days.

**Comment by ntoff** [comment] 2019-03-07 00:53
Hard to say in my case since it was so intermittent. I guess only time will tell.

**Comment by fredemmott** [comment] 2019-03-09 22:52
Ok, we've gone from several people having trouble in one day to no reports in a week - hopefully finally done with this :)

**Closed by fredemmott** 2019-03-09 22:52 UTC

**Comment by eliasthompson** [comment] 2019-03-21 09:10
Not sure when it happened (hadn't used it in a while and the computer did restart since), but it happened again. Using the reauthorize fixed it right up. Sorry I have no additional info.

**Comment by salvoza** [comment] 2019-04-04 01:56
I keep getting Authention_Failed errors

**Comment by bpwmd** [comment] 2020-09-03 05:34
can confirm this is still a problem today though my emote buttons also didnt work either. 
same with my system mic mute.
emotes fixed with a restart so may not be related. but the discord mute and the system mic mute had to be un installed and reinstalled even though the computer didnt get restarted.
