### ISSUE TITLE
Discord Authentication error

### ISSUE THREAD

**Issue by salvoza** [fredemmott/StreamDeck-Discord#9] opened 2019-04-04 19:41 UTC
**Describe the bug**
I have installed the latest version for the StreamDeck (version 2.2), followed the instructions and I get an Authentication Error

**To Reproduce**
1. Go to the Custom: Toggle Discord Mute
2. Click Reconnec tor Reuathenticate 
3. Click the Authorize button on the Discord popup

**Expected behavior**
The StreamDeck Toggle Mute button to work.

**Debugging Information**
![image](https://user-images.githubusercontent.com/9552431/55583386-ab39c680-5719-11e9-90f8-2b4f1dc89e6a.png)

**Log File**

20:40:57.418 Connecting to Discord
20:40:57.418 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
20:40:57.580 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
20:41:04.435 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
20:41:07.332 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:08.351 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:12.170 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:13.541 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:17.477 Property inspector event: com.fredemmott.discord.rpc.getState
20:41:18.619 Property inspector event: com.fredemmott.discord.rpc.reconnect
20:41:18.619 Connecting to Discord
20:41:18.620 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
20:41:18.847 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
20:41:23.974 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
20:41:28.427 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:41:28.876 Property inspector event: com.fredemmott.discord.rpc.getState
20:41:30.217 Key Up: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:41:33.038 Property inspector event: com.fredemmott.discord.rpc.reauthenticate
20:41:33.038 Connecting to Discord
20:41:33.040 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
20:41:33.167 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
20:41:34.980 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
20:41:37.099 Property inspector event: com.fredemmott.discord.rpc.reconnect
20:41:37.099 Connecting to Discord
20:41:37.102 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
20:41:37.261 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
20:41:39.278 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
20:41:40.938 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:42.001 Key Up: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:41:42.659 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:43.590 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:45.758 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:47.493 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:41:48.200 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:43:04.719 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:43:04.719 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:46:05.592 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:46:05.592 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:46:06.447 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:46:08.246 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:46:08.247 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:55:38.309 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:55:38.319 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:55:40.851 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
20:55:42.326 Key Up: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:55:50.702 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
20:55:51.783 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:11:56.072 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:11:56.616 Property inspector event: com.fredemmott.discord.rpc.getState
01:11:58.061 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:11:58.519 Property inspector event: com.fredemmott.discord.rpc.getState
01:11:59.977 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:12:04.330 Property inspector event: com.fredemmott.discord.rpc.reauthenticate
01:12:04.330 Connecting to Discord
01:12:04.333 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
01:12:04.530 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
01:12:07.655 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
01:12:12.888 Property inspector event: com.fredemmott.discord.rpc.reconnect
01:12:12.888 Connecting to Discord
01:12:12.890 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
01:12:13.015 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
01:12:19.160 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
01:12:29.379 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:12:30.803 Key Up: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:13:19.039 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:30:42.440 Key Up: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:30:43.443 Key Up: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:22.925 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:22.925 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:24.927 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:24.927 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:26.497 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:26.497 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:29.431 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:29.431 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:32.824 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:32.824 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:33.349 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:33.349 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:34.355 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:34.355 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:37:36.198 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:37:36.198 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:38:36.565 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:38:36.565 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:39:58.868 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:39:58.868 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:41:54.772 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:41:54.772 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:09.784 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:09.784 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:26.362 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:26.362 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:27.947 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:27.947 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:29.059 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:29.059 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:29.849 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:29.850 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:30.686 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:30.686 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:42:31.308 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:42:31.308 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:43:17.349 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:43:17.349 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:43:17.349 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:43:17.349 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:44:09.125 Will disappear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:44:09.125 Will disappear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4
01:44:09.125 Will appear: com.fredemmott.discord.mute 66662F322E253701473A08308A1E33C4
01:44:09.125 Will appear: com.fredemmott.discord.deafen 94452B0689EA3C1D5171FC0E970876D4

** Operating System **
Microsoft Windows 10 Enterprise

**Additional context**
Not Applicable

**Comment by fredemmott** [comment] 2019-04-04 20:43
so, it's not getting a successful response from Discord.

- is there an app id in the settings too? This should just be number. Make sure it exactly matches what you copied from the discord developer site
- is Discord prompting you for permission? If so, please attach screenshot of the prompt, and what button are you clicking?

**Comment by salvoza** [comment] 2019-04-04 22:24
It does the same thing when I press the Reconnect and the Reauthenticate buttons on the app opn StreamDeck

The screenshot of the auth request from Discord.

![image](https://user-images.githubusercontent.com/9552431/55592451-61100f80-5730-11e9-882b-4b429be26132.png)

The complete config screenshots (StreamDeck and Discord Dev site after)

![image](https://user-images.githubusercontent.com/9552431/55592483-6ff6c200-5730-11e9-9b54-802b1e11f9d1.png)

![image](https://user-images.githubusercontent.com/9552431/55592503-84d35580-5730-11e9-9423-9c6a7ce3b41d.png)

**Comment by salvoza** [comment] 2019-04-04 22:29
One other thing I should mention, I have 2FA enabled on my Discord account, would that cause an issue?

**Comment by fredemmott** [comment] 2019-04-04 22:35
Definitely not, I've got that too :)

So, with what you've posted:, and:

> 20:40:57.580 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
> 20:41:04.435 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0

- you've definitely got the app ID correct
- the local discord application is saying that you clicked cancel instead of authorize. Assuming that's not the case, double-check the client secret. Try both their copy button, or 'click to reveal' and typing it in by hand. I won't be able to test that this is what happens for a day or two. In theory, if the secret is wrong, Discord shouldn't have prompted you, but there's a chance there's a discord bug there.
- it's not getting far enough to ask Discord's API servers for the final token - this is all local so far. It should go REQUESTING_USER_PERMISSION -> REQUESTING_ACCESS_TOKEN -> AUTHENTICATING_WITH_ACCESS_TOKEN) -> REQUESTING_VOICE_STATE -> READY

**Comment by salvoza** [comment] 2019-04-04 22:40
I've done as you requested for the client secret and pasted them both in to notepad to check from the 'click to reveal' and the 'copy' option and they are both the same. I copied them both (paying attention to not collect a space at the end of the line) in to 'App Secret' and still the same thing.

Last night I even removed everything, regenerated the client secret and the same issue.

Should I log a bug with Discord?

**Comment by geewiz** [comment] 2019-05-02 11:21
Looks like I'm having the same problem but on macOS. I approve the app's confirmation request but it still results in `AUTHENTICATION_FAILED`.

```
12:17:06.4835 Property inspector event: com.fredemmott.discord.rpc.reauthenticate
12:17:06.4837 Connecting to Discord
12:17:06.4838 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
12:17:06.6217 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
12:17:09.8535 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0

12:18:55.2193 Property inspector event: com.fredemmott.discord.rpc.reconnect
12:18:55.2194 Connecting to Discord
12:18:55.2196 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
12:18:55.3684 Discord state change: rpcState = REQUESTING_USER_PERMISSION, muted = 0, deafened = 0
12:18:58.4694 Discord state change: rpcState = AUTHENTICATION_FAILED, muted = 0, deafened = 0
```

**Comment by nick22985** [comment] 2019-09-19 05:07
I am having the exact same issue. Did anyone get anywhere on this?

**Comment by salvoza** [comment] 2019-09-19 05:57
Nope, it was never resolved for me and then the author just stopped
responding :)

**Comment by nick22985** [comment] 2019-09-19 06:00
@salvoza I just fixed mine. the issue for me was that their was a blank redirect box in OAuth2 redirects. I just had to get rid of the blank one and it started working 
![image](https://user-images.githubusercontent.com/43774713/65217137-8635e600-daf6-11e9-9ace-e2ac1c935c58.png)

**Comment by salvoza** [comment] 2019-09-19 06:09
Wow, that's interesting. It never used to work with that setting as I had
already tried that. BUT it's working now! Thank you.

**Comment by geewiz** [comment] 2019-09-19 07:53
How strange, now it worked for me, too! I can only assume my redirect URL was missing the trailing slash.

**Comment by fredemmott** [comment] 2020-01-18 20:30
There's a few issues mentioned in the comments; some are needing to be really precise about the allowed origins, which I can't fix in the plugin - it must be exactly entered in the discord side.

For the intermittent issues, closing for more-detailed #15

Sorry for taking so long - it takes ~ 2 weeks to be able to reliably reproduce this enough to figure out a quicker way.

In short:
- tried looking for bugs, found lots of bugs on discord's end. Suspect current approach is unfixable
- tried a complete rewrite using a supported API. Not actually useful: only controls deafen/mute if the plugin initiates the call
- have one last near-rewrite to try using a different unsupported API

Might actually be unfixable, but not entirely out of options yet.

**Closed by fredemmott** 2020-01-18 20:30 UTC
