### ISSUE TITLE
Required to Authorize after every reboot

### ISSUE THREAD

**Issue by SkilledAlpaca** [fredemmott/StreamDeck-Discord#11] opened 2019-05-23 03:24 UTC
**Describe the bug**
After rebooting, required to re-authorize to get the buttons working again

**To Reproduce**
1. Reboot
2. Open StreamDeck software
3. Re-Authorize the addon

**Expected behavior**
Shouldn't need to do this every reboot

**Debugging Information**
Unavailable at time of post

**Log File**
https://gist.github.com/SkilledAlpaca/49959450655e060de5e0d18fc78248fc

** Operating System **
Windows 10 LTSB

**Comment by fredemmott** [comment] 2019-06-19 16:44
- Does this happen every time you reboot?
- If you reboot twice in a row, does it happen twice?
- Does it happen if you kill the streamdeck software from task manager and start it again?
- Does it happen if you restart discord when there is a discord update waiting to install?
- Does it happen if you restart discord and there is /not/ a discord update waiting to install?

I've not been able to intentionally reproduce this yet, but I have seen it a few times when Discord installs an update; given that Discord generally doesn't nag people to install updates - just installs them the next time it's started - it seems pretty likely that this issue is happening because rebooting happens to restart Discord when an update was ready. If that's the case, I can look into comparing versions and automatically reauthorizing

**Comment by fredemmott** [comment] 2020-01-18 20:29
Closing for more-detailed #15

Sorry for taking so long - it takes ~ 2 weeks to be able to reliably reproduce this enough to figure out a quicker way.

In short:
- tried looking for bugs, found lots of bugs on discord's end. Suspect current approach is unfixable
- tried a complete rewrite using a supported API. Not actually useful: only controls deafen/mute if the plugin initiates the call
- have one last near-rewrite to try using a different unsupported API

Might actually be unfixable, but not entirely out of options yet.

**Closed by fredemmott** 2020-01-18 20:29 UTC
