### ISSUE TITLE
restarted the computer now get yellow warning sign

### ISSUE THREAD

**Issue by bpwmd** [fredemmott/StreamDeck-Discord#28] opened 2020-08-30 18:54 UTC
i had this working last night but now I cant use the mute or deafen.
All i did was restart. i have re copied the info for both fields and tried the reconnect and reauthenticate as well.

I was able to get it to work after uninstall & reinstalling it but that seems silly to do every day.

**Comment by LucaKoval** [comment] 2020-09-01 07:20
I have a similar issue. Out of nowhere, neither mute nor deafen seems to be working. Yellow warning sign for both.

What exactly did you uninstall and reinstall?

**Comment by bpwmd** [comment] 2020-09-02 19:10
the custom extension itself

**Comment by HenryStratton** [comment] 2020-09-08 04:50
Interesting, this is the issue that led me to try and re-install the extension but now any attempt to re-install is met with failure, even after re-installing all of streamdeck :(

**Comment by bpwmd** [comment] 2020-09-09 22:06
so I am currently working with Elgato on this as it is not just the discord
button that this happens with. they had me back up my profile then
uninstall and reinstall the stream deck software. and then restore from the
backup. this has not worked and they are currently escalating it to a
senior tech so I will hopefully have an answer for you all. I do want to
take a moment and say thanks to Fredemmott for the bones of this and
hopefully, we can solve the issue. maybe make discord mute a standard
feature on the Elgato :)

**Comment by LucaKoval** [comment] 2020-09-09 22:09
Thank you for the update!

**Comment by fredemmott** [comment] 2020-09-09 22:29
Overall, I've been unable to reproduce this;  @bpwmd what are the other plugins you've seen this with? If it's the mute/deafen ones mentioned by @LucaKoval , they're related - it would also be good to know if Elgato's CPU plugin works for you

> maybe make discord mute a standard feature on the Elgato

A bit tangental to this issue, but this feels extremely unlike due to Discord's decisions: they want to entirely remove the ability for anything to control the local Discord application, except for "I'm now playing <x>" and their in-game chat/lobby integration.

This is also why this plugin is so annoying to set up: they will not give any applications the ability to do this any more, but they still allow it - for now - if the discord user is marked as a developer of the discord application.

At some point in the future, I expect Discord to entirely remove this functionality from the app, permanently breaking this plugin.

**Comment by fredemmott** [comment] 2020-09-09 22:32
- check your antivirus/windows defender
- check if your windows update history lines up with when this stopped working
- try the 'Release-StreamDeckPlugin' download on https://github.com/fredemmott/streamdeck-audiomute/actions/runs/180570260 - this changes how a few parts are packaged and signed, which may make windows happier with it

**Comment by NateStoneTV** [comment] 2020-09-16 00:04
I figure it was the newest update 4,8.2 I downgrade to Elgato Stream Deck 4.7 and it works fine again

**Comment by fredemmott** [comment] 2020-11-28 21:48
Closing; my biggest theory is that this is related to code signing and microsoft's increasing requirements for it. This would hopefully be resolved by https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v2.4rc2

If you are seeing similar issues, please re-open with current symptoms

**Closed by fredemmott** 2020-11-28 21:48 UTC

**Comment by pjchacong** [comment] 2021-05-12 14:17
Hello everybody!

I am just now having this same issue. I created a scene in OBS that only shows the video from my webcam. Nothing else. Whenever I try to move from another scene to this one on my Stream Deck, the button shows the alert sign and the scene doesn't change. 

I tried the workaround in this conversation. Backed up the profile, uninstalled the elgato software, rebooted my machine, installed stream deck again.

The only thing that failed is the backup file. I think it got corrupted at some point so I ended up recreating the profile and now everything works. However, I haven't tried rebooting my machine again. I'll do that later.

I have stream deck software version 4.9.4.13228, and my Windows is fully updated.
