### ISSUE TITLE
Plugin not giving me the option to install

### ISSUE THREAD

**Issue by N0N-afk** [fredemmott/StreamDeck-Discord#14] opened 2020-01-03 05:26 UTC
The plugin once opened, closes and does not give me the option to install the plugin directly to the Stream Deck app.

**Comment by fredemmott** [comment] 2020-01-03 05:41
Can you clarify what you mean by “opened”? Screenshots or videos may be useful.

**Comment by N0N-afk** [comment] 2020-01-03 07:31
I apologize, I mean I double clicked to open it and nothing came up.

**Comment by TheDankestJew** [comment] 2020-01-13 18:49
I am having the same issue when i double click the plugin there is nothing shown on the stream deck

**Comment by fredemmott** [comment] 2020-01-18 20:27
What is the thing you're double-clicking on? The .sdplugin file, the .exe, or something else?

**Comment by bennett-tl** [comment] 2020-01-26 20:31
I'm having issues trying to reinstall the plugin using the .sdplugin file. When double clicking the plugin file, stream deck flashes as if it registered that I wanted to install it, but does not ask me for the option of whether or not I would like to install it. Have tried restarting stream deck to see if that fixes it but it does not. Uninstalled it because thought reinstalling it would fix issues with it not working with discord (but I think it was because I had the original version you released and not this updated one)

**Comment by fredemmott** [comment] 2020-04-23 12:27
Closing: you need to contact Elgato support for this; the software is not attempting to load the plugin, so nothing the plugin can do.

**Closed by fredemmott** 2020-04-23 12:27 UTC

**Comment by fredemmott** [comment] 2020-04-23 12:31
I just accidentally reproduced this:

If you download it multiple times and end up with `com.fredemmott.discord.sdPlugin` and `com.fredemmott.discord (1).sdplugin`, this happens if you open the latter. Passing on to Elgato.
